//STEP 1. CREATE ACTION TYPES.
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//WE WILL SEND REQUEST TO BACK-END BY USING AXIOS ON ACTIONS FILE(EX. AUTH.JS) AND GET RESPONSE FROM BACK-END AND DISPATCH IT.
